# Generated by Django 2.2.4 on 2020-05-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_benevole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benevole',
            options={'verbose_name': 'Bénévole'},
        ),
        migrations.AlterField(
            model_name='benevole',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
