# Generated by Django 3.0.6 on 2020-05-26 19:31

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0002_delete_association'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('num_rna', models.CharField(max_length=50, null=True)),
                ('nom_association', models.CharField(max_length=200, null=True)),
                ('siege_social', models.CharField(max_length=1500, null=True)),
                ('date_creation', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Association',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
