# Generated by Django 2.2.4 on 2020-05-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200525_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benevole',
            name='phone_number',
        ),
    ]
