# Generated by Django 3.0.6 on 2020-05-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevole',
            name='adresse',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='benevole',
            name='ville',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
