# Generated by Django 3.0.6 on 2020-06-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200615_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='date_creation',
            field=models.DateTimeField(),
        ),
    ]
