# Generated by Django 3.0.6 on 2020-06-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200615_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='activite',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
