# Generated by Django 3.0.6 on 2020-06-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200621_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevole',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
