# Generated by Django 3.0.6 on 2020-06-27 11:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_benevole_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_location),
        ),
        migrations.AddField(
            model_name='benevole',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_location),
        ),
    ]
