# Generated by Django 3.0.6 on 2020-06-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200627_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='activite',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
