# Generated by Django 3.0.6 on 2020-06-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maraude', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maraude',
            name='benevole',
        ),
    ]
