# Generated by Django 3.0.6 on 2020-06-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maraude', '0002_remove_maraude_benevole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maraude',
        ),
    ]
