# Generated by Django 3.0.6 on 2020-06-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maraude', '0005_maraude_benevole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maraude',
            name='date',
        ),
        migrations.RemoveField(
            model_name='maraude',
            name='description',
        ),
    ]
