# Generated by Django 3.0.6 on 2020-06-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maraude', '0006_auto_20200606_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maraude',
        ),
    ]
