# Generated by Django 3.0.6 on 2020-06-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maraude', '0008_maraude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maraude',
        ),
    ]
