# Generated by Django 3.0.6 on 2020-06-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maraude', '0012_auto_20200610_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_arrondissement', models.CharField(choices=[('1er Arrondissement', '75101'), ('2e Arrondissement', '75102'), ('3e Arrondissement', '75103'), ('4e Arrondissement', '75104'), ('5e Arrondissement', '75105'), ('6e Arrondissement', '75106'), ('7e Arrondissement', '75107'), ('8e Arrondissement', '75108'), ('9e Arrondissement', '75109'), ('10e Arrondissement', '75110'), ('11e Arrondissement', '75111'), ('12e Arrondissement', '75112'), ('13e Arrondissement', '75113'), ('14e Arrondissement', '75114'), ('15e Arrondissement', '75115'), ('16e Arrondissement', '75116'), ('17e Arrondissement', '75117'), ('18e Arrondissement', '75118'), ('19e Arrondissement', '75119'), ('20e Arrondissement', '75120')], max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='maraude',
            name='arrondissement',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='maraude.Arrondissement'),
        ),
    ]
