# Generated by Django 3.0.6 on 2020-06-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200530_1147'),
        ('maraude', '0014_auto_20200612_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maraude',
            name='benevole',
            field=models.ManyToManyField(blank=True, related_name='maraude_benevole', to='users.Benevole'),
        ),
    ]
