# Generated by Django 3.0.6 on 2020-06-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maraude', '0015_auto_20200612_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.CharField(choices=[('Vetements', 'vetement'), ('Produits alimentaire', 'nourriture'), ('Service à la personne', 'service'), ('Boisson', 'boisson'), ('Dialogue', 'discussion'), ('Soin', 'soin'), ('Activité', 'activité'), ('Sensibilisation', 'sensibilisation')], max_length=1500, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='maraude',
            name='adresse',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='maraude',
            name='heure_debut',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='maraude',
            name='heure_fin',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='maraude',
            name='produit',
            field=models.ManyToManyField(blank=True, related_name='maraude_product', to='maraude.Product'),
        ),
    ]
