# Generated by Django 3.0.6 on 2020-06-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200615_1207'),
        ('maraude', '0016_auto_20200615_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maraude',
            name='association',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='my_maraude', to='users.Association'),
        ),
        migrations.AlterField(
            model_name='product',
            name='distribution',
            field=models.CharField(choices=[('Vetements', 'vetement'), ('Produits alimentaires', 'nourriture'), ('Services à la personne', 'service'), ('Boissons', 'boisson'), ('Dialogues', 'discussion'), ('Soins', 'soin'), ('Activités', 'activité'), ('Sensibilisation', 'sensibilisation')], max_length=1500, unique=True),
        ),
    ]
