# Generated by Django 3.0.6 on 2020-06-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maraude', '0018_auto_20200630_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maraude',
            name='heure_debut',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
